name: bayes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  # Data stack
  - pandas
  - numpy
  - scipy
  - openpyxl
  # Viz
  - matplotlib
  - seaborn
  # ML
  - scikit-learn
  - pip
